Numpy

In [ ]:
import numpy as np

Create Numpy Array from Python list

In [ ]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [ ]:
[3.14,4,1,2]

[3.14, 4, 1, 2]

In [ ]:
np.array([3.14,4,3,2])

array([3.14, 4.  , 3.  , 2.  ])

In [ ]:
np.array([1,2,3,4],dtype ="float32")

array([1., 2., 3., 4.], dtype=float32)

In [ ]:
a1 = np.array([1,2,3,4])

In [ ]:
a1

array([1, 2, 3, 4])

In [ ]:
type(a1)

numpy.ndarray

In [ ]:
a2 = np.array ([[1,2,3],
               [4,5,6]])

In [ ]:
a2.shape

(2, 3)

In [ ]:
a2.size

6

Create numpy array

**zeros, ones, full, arange,linspace**